<?php
/**
 * @file
 * User Notes Module
 */

/**
 * Implements hook_menu().
 */
function jdt_user_notes_menu() {
  // Note URL Pattern -> note/article_nid.
  $items = array();
  $items['jdt_user_notes/note/%node'] = array(
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jdt_user_notes_form_definition', 2),
    'access callback' => 'user_access',
    'access arguments' => array('jdt_user_notes_permission'),
    'file' => 'jdt_user_notes_crud.inc',
    'type' => MENU_CALLBACK,
  );
  // Introduce the Notes tab.
  // Check if note exists before showing the tab.
  $items['node/%node/view_notes'] = array(
    'title' => t('My Notes'),
    'description' => 'Display articles related to an article',
    'page callback' => 'jdt_user_notes_display_notes',
    'page arguments' => array(1),
    'access callback' => 'jdt_user_notes_note_exist',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function jdt_user_notes_permission() {
  return array(
    'jdt_user_notes_permission' => array(
      'title' => t('Administer Notes'),
      'description' => t('Perform administration tasks for notes.'),
    ),
  );
}

/**
 * Form definition.
 */
function jdt_user_notes_form_definition($form, &$form_state, $node) {
  global $user;
  $user_id = $user->uid;
  $nid = $node->nid;
  // Default value check
  // If default value exists in database use that as default value.
  // If default value does not exist - print empty.
  $result = jdt_user_notes_entry_load($nid, $user_id);
  // Set values for note and note id.
  if (isset($result['note_text'])) {
    $default_value_note = $result['note_text'];
  }
  else {
    $default_value_note = '';
  }
  if (isset($result['note_id'])) {
    $default_note_id = $result['note_id'];
  }
  else {
    // If a note does not exist - generate a random note id.
    $nid_rand = rand();
    $default_note_id = $nid_rand;
  }
  $form['fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Note to Article'),
    '#default_value' => 'Hello',
  );
  $form['fieldset']['note_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Note'),
    '#default_value' => $default_value_note,
  );
  // Grab value for node id and make it part of the form state.
  $form['nid'] = array(
    '#type' => 'value',
    '#value' => $nid,
  );
  // Make User ID available to the form.
  $form['uid'] = array(
    '#type' => 'value',
    '#value' => $user_id,
  );
  // Make Note ID available to the form.
  $form['note_id'] = array(
    '#type' => 'value',
    '#value' => $default_note_id,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Note'),
  );
  return $form;
}

/**
 * Submit Button handler.
 */
function jdt_user_notes_form_definition_submit($form, &$form_state) {
  // Grab values from the form state.
  $values = $form_state['values'];
  dsm($values);
  $entry = array(
    'article_nid' => $form_state['values']['nid'],
    'note_text'   => $form_state['values']['note_textfield'],
    'author_uid'  => $form_state['values']['uid'],
    'note_id'     => $form_state['values']['note_id'],
  );
  jdt_user_notes_update($entry);
  drupal_set_message(t('Your note has been added'));
}

/**
  * Show related notes to an article.
  */
function jdt_user_notes_display_notes($node) {
  global $user;
  $user_id = $user->uid;
  $node_id = $node->nid;
  // Initialize default values of variables
  // If no values exist, then default values get populated
  $vars = array('NOTE_TEXT' => 'NOTE_TEXT', 'NODE_TITLE' => 'NODE_TITLE', 'NODE_AUTHOR' => 'NODE_AUTHOR');
  // Return Node Title
  $node_title = $node->title;
  // Return Node Author
  //dsm(user_load($node->uid));
  $node_author = $user->name;
  module_load_include('inc', 'jdt_user_notes', 'jdt_user_notes_crud');
  $load_articles = jdt_user_notes_entry_load($user_id,$node_id);
  //dsm($load_articles);
  return array(
     '#theme' => 'jdt-user-notes',
     '#NOTE_TEXT' => $articles,
     '#NODE_TITLE' => $node_title,
     '#NODE_AUTHOR' => $node_author,
  );
}

/**
 * Create tab for notes only if notes exist for an article.
 */
function jdt_user_notes_note_exist($node) {
  global $user;
  $user_id = $user->uid;
  $node_id = $node->nid;
  module_load_include('inc', 'jdt_user_notes', 'jdt_user_notes_crud');
  $load_values = jdt_user_notes_entry_load($node_id,$user_id);
  if(isset($load_values['note_text'])) {
    return TRUE;
  }
  return FALSE;
}

/**
  * Hook Theme
  */
function jdt_user_notes_theme() {
  return array(
    // PLACEHOLDERS to hold initial values
    'jdt-user-notes' => array(
       'variables' => array(
          'NOTE_TEXT' => 'Test Note linked to test node',
          'NODE_TITLE' => 'Test Node',
          'NODE_AUTHOR' => 'Test Node Author',
       ),
       'template' => 'theme/jdt_user_notes_theming',
    ),
  );
}
